//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomestayDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int CommentID { get; set; }
        public int UserID { get; set; }
        public int HouseID { get; set; }
        public System.DateTime CommentDate { get; set; }
        public string Details { get; set; }
    
        public virtual House House { get; set; }
        public virtual User User { get; set; }
    }
}
