//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomestayDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class House
    {
        public House()
        {
            this.Bookings = new HashSet<Booking>();
            this.Comments = new HashSet<Comment>();
            this.ImageSavers = new HashSet<ImageSaver>();
            this.RatingLogs = new HashSet<RatingLog>();
        }
    
        public int HouseID { get; set; }
        public int UserID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Title { get; set; }
        public string Detail { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Address { get; set; }
        public string AvailableDate { get; set; }
        public int HouseScore { get; set; }
        public int NORating { get; set; }
        public Nullable<System.DateTime> RatingDate { get; set; }
    
        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<ImageSaver> ImageSavers { get; set; }
        public virtual ICollection<RatingLog> RatingLogs { get; set; }
    }
}
