//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomestayDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageSaver
    {
        public int ImageID { get; set; }
        public int HouseID { get; set; }
        public byte[] Image { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual House House { get; set; }
    }
}
