//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomestayDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Bookings = new HashSet<Booking>();
            this.Comments = new HashSet<Comment>();
            this.Houses = new HashSet<House>();
            this.RatingLogs = new HashSet<RatingLog>();
            this.ScoreLogs = new HashSet<ScoreLog>();
            this.ScoreLogs1 = new HashSet<ScoreLog>();
        }
    
        public int UserID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public string Address { get; set; }
        public Nullable<decimal> Phone { get; set; }
        public string Email { get; set; }
        public Nullable<int> UserScore { get; set; }
        public Nullable<System.DateTime> ScoreDate { get; set; }
    
        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<House> Houses { get; set; }
        public virtual ICollection<RatingLog> RatingLogs { get; set; }
        public virtual ICollection<ScoreLog> ScoreLogs { get; set; }
        public virtual ICollection<ScoreLog> ScoreLogs1 { get; set; }
    }
}
